package postman

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

type PostmanCollection struct {
	Info                    Info                    `json:"info"`
	Item                    []PostmanCollectionItem `json:"item"`
	ProtocolProfileBehavior ProtocolProfileBehavior `json:"protocolProfileBehavior"`
}

type Info struct {
	PostmanID   string `json:"_postman_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Schema      string `json:"schema"`
}

type PostmanCollectionItem struct {
	Name                    string                  `json:"name"`
	Item                    []ItemItem              `json:"item"`
	Description             string                  `json:"description"`
	ProtocolProfileBehavior ProtocolProfileBehavior `json:"protocolProfileBehavior"`
	Event                   []Event                 `json:"event"`
}

type Event struct {
	Listen string `json:"listen"`
	Script Script `json:"script"`
}

type Script struct {
	ID   string   `json:"id"`
	Type string   `json:"type"`
	Exec []string `json:"exec"`
}

type ItemItem struct {
	Name     string        `json:"name"`
	Request  Request       `json:"request"`
	Response []interface{} `json:"response"`
}

type Request struct {
	Method      Method        `json:"method"`
	Header      []interface{} `json:"header"`
	Body        Body          `json:"body"`
	URL         URL           `json:"url"`
	Description *string       `json:"description,omitempty"`
}

type Body struct {
	Mode     Mode        `json:"mode"`
	Formdata []Formdatum `json:"formdata"`
	Options  Options     `json:"options"`
}

type Formdatum struct {
	Key   string  `json:"key"`
	Value *string `json:"value,omitempty"`
	Type  Type    `json:"type"`
	Src   *string `json:"src,omitempty"`
}

type Options struct {
	Raw Raw `json:"raw"`
}

type Raw struct {
	Language Language `json:"language"`
}

type URL struct {
	Raw      string   `json:"raw"`
	Protocol Protocol `json:"protocol"`
	Host     []Host   `json:"host"`
	Port     string   `json:"port"`
	Path     []string `json:"path"`
}

type ProtocolProfileBehavior struct {
}

type Type string

const (
	File Type = "file"
	Text Type = "text"
)

type Mode string

const (
	Formdata Mode = "formdata"
)

type Language string

const (
	JSON Language = "json"
)

type Method string

const (
	Post Method = "POST"
)

type Host string

const (
	Localhost Host = "localhost"
)

type Protocol string

const (
	HTTP Protocol = "http"
)
